[tools]
zig = "0.15.2"
uv = "0.11.6"

[tasks]
build = { run = "zig build workloads gem5" }
setup-tex = { run = ["tlmgr install dvipng type1cm cm-super underscore ieeetran embedfile", "mktexlsr"], tools = { tinytex = "2026.04" } }
simulate = { run = "zig build simulations" }
report = { depends = ["setup-tex"], run = "zig build report" }
